name: Publish to PyPI
on:
  release:
    types: [ published ]
    branches:
      - main
    workflow_dispatch:
jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4
      - name: Install venv
        run: poetry install
      #      - run: poetry run pytest
      - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Publish package
        run: poetry publish --build
